-- =============================================================================
-- 20260347: أرشفة سبب الحذف + تنفيذ الحذف المتسلسل (عبر owner_delete_property_cascade)
--           + جدول رسائل العقد (دردشة مرتبطة بالعقد)
-- ينفَّذ بعد 20260346_unified_national_login_listing_numeric.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1) أرشفة طلبات/أسباب الحذف قبل التنفيذ الفعلي
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.property_delete_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id uuid NOT NULL,
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  reason text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_property_delete_audit_property
  ON public.property_delete_audit (property_id);

COMMENT ON TABLE public.property_delete_audit IS
  'سجل أسباب حذف العقار قبل التنفيذ الفعلي (owner_delete_property_cascade).';

-- ---------------------------------------------------------------------------
-- 2) request_property_delete: يتحقق من المالك، يسجل السبب، ثم الحذف المتسلسل
-- ---------------------------------------------------------------------------
-- إن وُجدت دالة بنفس الاسم بنوع إرجاع مختلف، يجب حذفها أولاً (42P13).
DROP FUNCTION IF EXISTS public.request_property_delete(uuid, text);

CREATE OR REPLACE FUNCTION public.request_property_delete(
  p_property_id uuid,
  p_reason text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
  oid uuid;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated';
  END IF;

  SELECT owner_id INTO oid FROM public.properties WHERE id = p_property_id LIMIT 1;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'property_not_found';
  END IF;
  IF oid IS DISTINCT FROM uid THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  INSERT INTO public.property_delete_audit (property_id, owner_id, reason)
  VALUES (
    p_property_id,
    uid,
    left(coalesce(p_reason, ''), 2000)
  );

  SELECT public.owner_delete_property_cascade(p_property_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.request_property_delete(uuid, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 3) رسائل العقد (دردشة جانبية أثناء التعاقد)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.listing_contract_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL REFERENCES public.listing_contracts (id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  body text NOT NULL,
  message_type text NOT NULL DEFAULT 'chat',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT chk_listing_contract_messages_type CHECK (
    length(trim(message_type)) > 0 AND length(trim(body)) > 0
  )
);

CREATE INDEX IF NOT EXISTS idx_listing_contract_messages_contract_created
  ON public.listing_contract_messages (contract_id, created_at DESC);

COMMENT ON TABLE public.listing_contract_messages IS
  'رسائل مرتبطة بعقد تسويق: chat، request_change، request_cancel، إلخ.';

ALTER TABLE public.listing_contract_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS lcm_select_parties ON public.listing_contract_messages;
CREATE POLICY lcm_select_parties ON public.listing_contract_messages
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.listing_contracts c
      WHERE c.id = contract_id
        AND (c.owner_id = auth.uid() OR c.marketer_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS lcm_insert_parties ON public.listing_contract_messages;
CREATE POLICY lcm_insert_parties ON public.listing_contract_messages
  FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.listing_contracts c
      WHERE c.id = contract_id
        AND (c.owner_id = auth.uid() OR c.marketer_id = auth.uid())
    )
  );

-- ---------------------------------------------------------------------------
-- 4) خطاف خفيف لفحص انتهاء الوثائق (يُستدعى يدوياً أو من pg_cron لاحقاً)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.run_document_expiry_checks()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF to_regclass('public.user_compliance_documents') IS NULL THEN
    RETURN;
  END IF;

  UPDATE public.user_compliance_documents u
  SET
    status = 'expired',
    updated_at = timezone('utc', now())
  WHERE u.expires_at IS NOT NULL
    AND u.expires_at < (timezone('utc', now()))::date
    AND u.status NOT IN ('expired', 'rejected', 'missing');

  UPDATE public.user_compliance_documents u
  SET
    status = 'expiring_soon',
    updated_at = timezone('utc', now())
  WHERE u.status = 'valid'
    AND u.expires_at IS NOT NULL
    AND u.expires_at >= (timezone('utc', now()))::date
    AND u.expires_at <= (timezone('utc', now()) + interval '30 days')::date;
END;
$$;

COMMENT ON FUNCTION public.run_document_expiry_checks IS
  'تحديث حالات user_compliance_documents؛ جدول pg_cron يستدعيها دورياً عند التفعيل.';
