// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Jumx3edRucy9Yj53A5GH50OJigb2oX4',
    appId: '1:396763698740:web:0394828ec9dfa6d8b61c61',
    messagingSenderId: '396763698740',
    projectId: 'aqaruser-73df0',
    authDomain: 'aqaruser-73df0.firebaseapp.com',
    storageBucket: 'aqaruser-73df0.firebasestorage.app',
    measurementId: 'G-CX3TTB2CDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXeBbqw_c48WNfkb5CqyXgIngnF0JKi0',
    appId: '1:396763698740:android:9ef992bd3c1595e2b61c61',
    messagingSenderId: '396763698740',
    projectId: 'aqaruser-73df0',
    storageBucket: 'aqaruser-73df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHU9tKny8RYpA50GqS-efw2Cu1SLgrjCs',
    appId: '1:396763698740:ios:ed8dc56f130fb87cb61c61',
    messagingSenderId: '396763698740',
    projectId: 'aqaruser-73df0',
    storageBucket: 'aqaruser-73df0.firebasestorage.app',
    iosBundleId: 'com.example.aqarUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHU9tKny8RYpA50GqS-efw2Cu1SLgrjCs',
    appId: '1:396763698740:ios:ed8dc56f130fb87cb61c61',
    messagingSenderId: '396763698740',
    projectId: 'aqaruser-73df0',
    storageBucket: 'aqaruser-73df0.firebasestorage.app',
    iosBundleId: 'com.example.aqarUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Jumx3edRucy9Yj53A5GH50OJigb2oX4',
    appId: '1:396763698740:web:190582ab60ff0342b61c61',
    messagingSenderId: '396763698740',
    projectId: 'aqaruser-73df0',
    authDomain: 'aqaruser-73df0.firebaseapp.com',
    storageBucket: 'aqaruser-73df0.firebasestorage.app',
    measurementId: 'G-MTSZJNK1TS',
  );
}
