// lib/main.dart
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

// ✅ Firebase
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // ✅ generated by flutterfire configure

// ✅ Provider
import 'package:provider/provider.dart';

// ✅ Session
import 'core/session/app_session.dart';

// ✅ L10n
import 'package:aqar_user/l10n/app_localizations.dart';

import 'shared/core/supabase_config.dart';
import 'screens/login_screen.dart';
import 'screens/user_dashboard.dart';
import 'screens/verify_screen.dart';
import 'screens/settings_page.dart';
import 'screens/reset_password_screen.dart';
import 'screens/gate_screen.dart';
import 'screens/fast_login_screen.dart';
import 'screens/password_setup.dart';
import 'screens/entry_choice_screen.dart';

import 'services/inactivity_service.dart';
import 'services/connectivity_guard.dart';
import 'theme.dart';

// ✅ Notifications
import 'services/notification_service.dart';

final ValueNotifier<ThemeMode> themeModeNotifier =
    ValueNotifier<ThemeMode>(ThemeMode.system);

// ✅ مصدر واحد للغة في كل التطبيق
final ValueNotifier<String> langNotifier = ValueNotifier<String>('ar');

// ✅ فلاغ عالمي يمنع أي Redirect للداشبورد أثناء Recovery
final ValueNotifier<bool> recoveryFlowNotifier = ValueNotifier<bool>(false);

// ✅ مفاتيح موحدة
const String kPrefGuestMode = 'guest_mode'; // bool
const String kPrefEntryMode = 'entry_mode'; // 'guest' | 'user'
const String kPrefFastLoginEnabled = 'fast_login_enabled'; // bool
const String kPrefFastLoginPinSet = 'fast_login_pin_set'; // bool
String otpVerifiedKey(String uid) => 'otp_verified_$uid';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ (تشخيص) التقاط أخطاء Flutter
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    debugPrint('FlutterError: ${details.exception}');
    debugPrint('${details.stack}');
  };

  // ✅ تحميل تفضيلات (لغة + ثيم)
  final prefs = await SharedPreferences.getInstance();
  final savedLang = prefs.getString('language') ?? 'ar';
  final savedTheme = prefs.getString('themeMode') ?? ThemeMode.system.name;

  langNotifier.value = (savedLang == 'en') ? 'en' : 'ar';
  themeModeNotifier.value = ThemeMode.values.firstWhere(
    (e) => e.name == savedTheme,
    orElse: () => ThemeMode.system,
  );

  // ✅ Supabase init
  await Supabase.initialize(
    url: SupabaseConfig.supabaseUrl,
    anonKey: SupabaseConfig.supabaseAnonKey,
  );

  // ✅ Firebase init (باستخدام firebase_options)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ✅ IMPORTANT: لا تجعل NotificationService يمنع الإقلاع (تجنب التعليق)
  unawaited(
    NotificationService.init()
        .timeout(const Duration(seconds: 6), onTimeout: () => null)
        .catchError((e, st) {
      debugPrint('NotificationService.init error: $e');
      debugPrint('$st');
    }),
  );

  // ✅ عند فتح رابط Recovery على الويب (قبل listener)
  recoveryFlowNotifier.value = _isRecoveryUrlOrCode();

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppSession(),
      child: const AqarUserApp(),
    ),
  );
}

class AqarUserApp extends StatefulWidget {
  const AqarUserApp({super.key});

  @override
  State<AqarUserApp> createState() => _AqarUserAppState();
}

class _AqarUserAppState extends State<AqarUserApp> with WidgetsBindingObserver {
  final GlobalKey<NavigatorState> _navKey = GlobalKey<NavigatorState>();
  StreamSubscription<AuthState>? _sub;

  late final InactivityService _inactivity;

  bool _navigating = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);

    final Duration idle;
    final Duration countdown;
    if (kIsWeb) {
      idle = const Duration(minutes: 10);
      countdown = const Duration(minutes: 2);
    } else {
      idle = const Duration(minutes: 5);
      countdown = const Duration(minutes: 1);
    }

    _inactivity = InactivityService(
      navigatorKey: _navKey,
      idleBeforePrompt: idle,
      promptCountdown: countdown,
    );
    _inactivity.start();

    _sub = Supabase.instance.client.auth.onAuthStateChange.listen((data) async {
      final event = data.event;

      // ✅ عند تسجيل الدخول/تحديث التوكن: زامن FCM token (لكن لا تعلق)
      if (data.session != null &&
          (event == AuthChangeEvent.signedIn ||
              event == AuthChangeEvent.tokenRefreshed ||
              event == AuthChangeEvent.userUpdated)) {
        unawaited(
          NotificationService.init()
              .timeout(const Duration(seconds: 6), onTimeout: () => null)
              .catchError((e, st) {
            debugPrint('NotificationService.init (auth change) error: $e');
            debugPrint('$st');
          }),
        );
      }

      // ✅ Recovery
      if (event == AuthChangeEvent.passwordRecovery) {
        recoveryFlowNotifier.value = true;
        _safeNavTo('/resetPassword');
        return;
      }

      // ✅ SignedOut
      if (event == AuthChangeEvent.signedOut) {
        recoveryFlowNotifier.value = false;

        final ctx = _navKey.currentContext;
        if (ctx != null) {
          try {
            ctx.read<AppSession>().logout();
          } catch (_) {}
        }

        _safeNavTo('/');
        return;
      }
    });

    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_isRecoveryUrlOrCode()) {
        recoveryFlowNotifier.value = true;
        _safeNavTo('/resetPassword');
      }
    });
  }

  void _safeNavTo(String route) {
    if (_navigating) return;

    final nav = _navKey.currentState;
    if (nav == null) return;

    final ctx = _navKey.currentContext;
    final currentName = ModalRoute.of(ctx ?? nav.context)?.settings.name ?? '';
    if (currentName == route) return;

    _navigating = true;
    try {
      nav.pushNamedAndRemoveUntil(route, (r) => false);
    } finally {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        _navigating = false;
      });
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _sub?.cancel();
    _inactivity.stop();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (recoveryFlowNotifier.value == true) return;

    if (state == AppLifecycleState.paused ||
        state == AppLifecycleState.inactive) {
      _inactivity.lockNow();
    }
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeMode>(
      valueListenable: themeModeNotifier,
      builder: (context, mode, _) {
        return ValueListenableBuilder<String>(
          valueListenable: langNotifier,
          builder: (context, lang, __) {
            final isRtl = (lang == 'ar');

            return MaterialApp(
              navigatorKey: _navKey,
              debugShowCheckedModeBanner: false,
              localizationsDelegates: AppLocalizations.localizationsDelegates,
              supportedLocales: AppLocalizations.supportedLocales,
              locale: Locale(lang),
              onGenerateTitle: (context) =>
                  AppLocalizations.of(context)?.appTitle ?? 'Aqar User',
              theme: AppTheme.lightTheme,
              darkTheme: AppTheme.darkTheme,
              themeMode: mode,
              initialRoute: '/',
              builder: (context, child) {
                Widget wrapped = child ?? const SizedBox.shrink();

                wrapped = Focus(
                  autofocus: true,
                  onKeyEvent: (node, event) {
                    _inactivity.userActivity();
                    return KeyEventResult.ignored;
                  },
                  child: Listener(
                    behavior: HitTestBehavior.translucent,
                    onPointerDown: (_) => _inactivity.userActivity(),
                    onPointerMove: (_) => _inactivity.userActivity(),
                    onPointerSignal: (_) => _inactivity.userActivity(),
                    child: wrapped,
                  ),
                );

                // ✅ Web traversal policy fix
                if (kIsWeb) {
                  wrapped = FocusTraversalGroup(
                    policy: WidgetOrderTraversalPolicy(),
                    child: wrapped,
                  );
                }

                return Directionality(
                  textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
                  child: wrapped,
                );
              },
              routes: {
                '/': (context) => StartRouter(lang: lang),
                '/gate': (context) => const GateScreen(),
                '/entryChoice': (context) => const EntryChoiceScreen(),
                '/login': (context) => const LoginScreen(),
                '/verify': (context) => const VerifyScreen(),
                '/resetPassword': (context) => const ResetPasswordScreen(),
                '/passwordSetup': (context) => const PasswordSetupScreen(),
                '/userDashboard': (context) => UserDashboard(
                      key: const ValueKey('dashboard'),
                      lang: lang,
                    ),
                '/settings': (context) => SettingsPage(lang: lang),
                '/fastLogin': (context) => const FastLoginScreen(),
              },
            );
          },
        );
      },
    );
  }
}

class StartRouter extends StatefulWidget {
  final String lang;
  const StartRouter({super.key, required this.lang});

  @override
  State<StartRouter> createState() => _StartRouterState();
}

class _StartRouterState extends State<StartRouter> {
  bool _loading = true;
  Widget? _target;

  bool _offline = false;
  bool _retryingNet = false;

  bool get _isMobile =>
      !kIsWeb &&
      (defaultTargetPlatform == TargetPlatform.android ||
          defaultTargetPlatform == TargetPlatform.iOS);

  @override
  void initState() {
    super.initState();
    _resolve();
  }

  // ✅ لا تجعل فحص الإنترنت يعلّق الإقلاع
  Future<bool> _hasInternet() async {
    try {
      return await ConnectivityGuard.hasInternet()
          .timeout(const Duration(seconds: 6), onTimeout: () => true);
    } catch (_) {
      return true;
    }
  }

  Future<void> _retryInternet() async {
    if (_retryingNet) return;
    setState(() => _retryingNet = true);
    try {
      final ok = await _hasInternet();
      if (!mounted) return;

      if (!ok) {
        setState(() {
          _offline = true;
          _retryingNet = false;
        });
        return;
      }

      setState(() {
        _offline = false;
        _retryingNet = false;
        _loading = true;
      });

      await _resolve();
    } finally {
      if (mounted) setState(() => _retryingNet = false);
    }
  }

  Future<void> _resolve() async {
    // 0) Recovery always allowed
    if (_isRecoveryUrlOrCode()) {
      if (!mounted) return;
      setState(() {
        _target = const ResetPasswordScreen();
        _loading = false;
        _offline = false;
      });
      return;
    }

    // ✅ منع البداية بدون إنترنت (لكن مع timeout)
    final okNet = await _hasInternet();
    if (!mounted) return;
    if (!okNet) {
      setState(() {
        _offline = true;
        _loading = false;
        _target = OfflineGate(
          lang: widget.lang,
          retrying: _retryingNet,
          onRetry: _retryInternet,
        );
      });
      return;
    }

    final prefs = await SharedPreferences.getInstance();

    final String entryMode =
        (prefs.getString(kPrefEntryMode) ?? '').trim().toLowerCase();
    final bool guestMode = prefs.getBool(kPrefGuestMode) ?? false;

    final bool fastEnabled = prefs.getBool(kPrefFastLoginEnabled) ?? false;
    final bool pinSet = prefs.getBool(kPrefFastLoginPinSet) ?? false;

    final sb = Supabase.instance.client;
    final session = sb.auth.currentSession;

    // 1) لو يوجد Session -> Dashboard
    if (session != null) {
      final uid = sb.auth.currentUser?.id ?? '';

      final verified = (uid.isNotEmpty)
          ? (prefs.getBool(otpVerifiedKey(uid)) ?? false)
          : false;

      if (verified) {
        try {
          await prefs.setBool(kPrefGuestMode, false);
          await prefs.setString(kPrefEntryMode, 'user');
        } catch (_) {}

        if (mounted && uid.isNotEmpty) {
          try {
            await context.read<AppSession>().setUser(uid);
          } catch (_) {}
        }

        // ✅ لا تعلق
        unawaited(
          NotificationService.init()
              .timeout(const Duration(seconds: 6), onTimeout: () => null)
              .catchError((_) {}),
        );

        if (!mounted) return;
        setState(() {
          _target = UserDashboard(
            key: const ValueKey('dashboard'),
            lang: widget.lang,
          );
          _loading = false;
          _offline = false;
        });
        return;
      }

      // Session موجودة لكن OTP غير موثّق -> Login/FastLogin
      try {
        if (uid.isNotEmpty) {
          await prefs.remove(otpVerifiedKey(uid));
        }
        await prefs.setBool(kPrefGuestMode, false);
        await prefs.setString(kPrefEntryMode, 'user');
      } catch (_) {}

      if (mounted) {
        try {
          await context.read<AppSession>().setGuest();
        } catch (_) {}
      }

      if (!mounted) return;
      setState(() {
        _target = _isMobile && fastEnabled && pinSet
            ? const FastLoginScreen()
            : const LoginScreen();
        _loading = false;
        _offline = false;
      });
      return;
    }

    // 2) لا يوجد Session -> entry_mode
    final bool isGuest = guestMode || entryMode == 'guest';

    if (isGuest) {
      if (mounted) {
        try {
          await context.read<AppSession>().setGuest();
        } catch (_) {}
      }

      if (!mounted) return;
      setState(() {
        _target = UserDashboard(
          key: const ValueKey('dashboard'),
          lang: widget.lang,
        );
        _loading = false;
        _offline = false;
      });
      return;
    }

    // 3) entry_mode=user
    if (entryMode == 'user') {
      if (mounted) {
        try {
          await context.read<AppSession>().setGuest();
        } catch (_) {}
      }

      if (!mounted) return;
      setState(() {
        _target = _isMobile && fastEnabled && pinSet
            ? const FastLoginScreen()
            : const LoginScreen();
        _loading = false;
        _offline = false;
      });
      return;
    }

    // 4) أول تشغيل
    if (mounted) {
      try {
        await context.read<AppSession>().setGuest();
      } catch (_) {}
    }

    if (!mounted) return;
    setState(() {
      _target = const EntryChoiceScreen();
      _loading = false;
      _offline = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }
    return _target ?? const SizedBox.shrink();
  }
}

class OfflineGate extends StatelessWidget {
  final String lang;
  final bool retrying;
  final VoidCallback onRetry;

  const OfflineGate({
    super.key,
    required this.lang,
    required this.retrying,
    required this.onRetry,
  });

  bool get _isAr => lang.toLowerCase() != 'en';

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    final bg = isDark ? const Color(0xFF0B1220) : const Color(0xFFF5F7FA);
    final card = isDark ? const Color(0xFF121A2A) : Colors.white;
    final title = isDark ? Colors.white : const Color(0xFF0B1220);
    final sub = isDark ? const Color(0xFFCBD5E1) : const Color(0xFF475569);

    return Directionality(
      textDirection: _isAr ? TextDirection.rtl : TextDirection.ltr,
      child: Scaffold(
        backgroundColor: bg,
        body: SafeArea(
          child: Center(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 420),
              child: Card(
                color: card,
                elevation: 14,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(22),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(18),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.wifi_off_rounded, size: 56, color: title),
                      const SizedBox(height: 10),
                      Text(
                        _isAr
                            ? 'لا يوجد اتصال بالإنترنت'
                            : 'No internet connection',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          fontWeight: FontWeight.w900,
                          fontSize: 16,
                          color: title,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        _isAr
                            ? 'لن يبدأ التطبيق بدون إنترنت. فعّل الإنترنت ثم أعد المحاولة.'
                            : 'The app cannot start without internet. Enable internet then retry.',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          fontWeight: FontWeight.w800,
                          color: sub,
                          height: 1.35,
                        ),
                      ),
                      const SizedBox(height: 14),
                      SizedBox(
                        width: double.infinity,
                        height: 48,
                        child: ElevatedButton.icon(
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0xFF0F766E),
                            foregroundColor: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(14),
                            ),
                          ),
                          onPressed: retrying ? null : onRetry,
                          icon: retrying
                              ? const SizedBox(
                                  width: 16,
                                  height: 16,
                                  child: CircularProgressIndicator(
                                    strokeWidth: 2,
                                    color: Colors.white,
                                  ),
                                )
                              : const Icon(Icons.refresh_rounded),
                          label: Text(_isAr ? 'إعادة المحاولة' : 'Retry'),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

/// ✅ فحص: type=recovery أو وجود code (PKCE) أو access_token في fragment
bool _isRecoveryUrlOrCode() {
  if (!kIsWeb) return false;

  try {
    final uri = Uri.base;

    final qType = (uri.queryParameters['type'] ?? '').toLowerCase();
    if (qType == 'recovery') return true;

    if (uri.queryParameters.containsKey('code')) return true;

    final frag = uri.fragment;
    if (frag.isNotEmpty) {
      final fragParams = Uri.splitQueryString(frag);
      final fType = (fragParams['type'] ?? '').toLowerCase();
      if (fType == 'recovery') return true;

      if (fragParams.containsKey('access_token')) return true;
    }

    return false;
  } catch (_) {
    return false;
  }
}
